# https://taskfile.dev
version: "3"
dotenv:
  - ~/export-esp.sh
tasks:
  install-espflash:
    status:
      - which cargo-espflash
    cmds:
      - cargo install cargo-espflash

  build:
    desc: Build firmware and save it in the firefly-updates directory.
    cmds:
      - >
        cargo espflash save-image
        --skip-update-check
        --features v2
        --chip esp32s3
        --release
        {{.CLI_ARGS}}
        ../firefly-updates/firefly-main

  write-serial:
    desc: Write the serial number to the device's flash.
    cmds:
      - task: install-espflash
      - python3 -c 'open("/tmp/serial.txt", "wb").write((1337).to_bytes(4))'
      - defer: rm /tmp/serial.txt
      - >
        cargo espflash write-bin
        --skip-update-check
        --chip esp32s3
        0x10000
        /tmp/serial.txt

  flash:
    desc: Build the firmware and write it to the device connected via USB.
    cmds:
      - task: install-espflash
      - task: write-serial
      # Switch OTA to the factory slot
      - >
        cargo espflash erase-parts
        --partition-table partitions.csv
        otadata
      - >
        cargo espflash flash
        --skip-update-check
        --chip                  esp32s3
        --partition-table       partitions.csv
        --target-app-partition  factory
        --release
        {{.CLI_ARGS}}

  monitor:
    cmds:
      - task: install-espflash
      - cargo espflash monitor {{.CLI_ARGS}}
